apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cocalc-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/limit-connections: '200'
    nginx.ingress.kubernetes.io/limit-rps: '25'
    nginx.ingress.kubernetes.io/limit-rpm: '60'
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  tls:
  - hosts:
    - mlhep-test.coresearch.club
    secretName: cocalc-tls
  rules:
  - host: mlhep-test.coresearch.club
    http:
      paths:
       -  backend:
            serviceName: cocalc-svc
            servicePort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: cocalc-svc
spec:
#  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: cocalc
---
apiVersion: apps/v1
kind: Deployment
metadata:
#  annotations:
#    deployment.kubernetes.io/revision: '1'
#  labels:
#    app: cocalc
  name: cocalc
spec:
  minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: cocalc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cocalc
    spec:
      containers:
      - env:
        - name: KUBERNETES_REGISTRY
          value: vbelavin 
        #image: sagemathinc/cocalc-kubernetes-server:latest
        image: marts2007/cocalc-kubernetes-server
        name: cocalc
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 2049
          name: nfs
        - containerPort: 20048
          name: mountd
        - containerPort: 111
          name: rpcbind
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /projects
          name: cocalc-projects-storage
        - name: azure-backup
          mountPath: backup
      serviceAccountName: cocalc-kubernetes-server
      terminationGracePeriodSeconds: 15
      volumes:
        - name: cocalc-projects-storage
          persistentVolumeClaim:
            claimName: cocalc-projects-claim
        - name: azure-backup
          azureFile:
            secretName: azure-secret-cocalc
            shareName: cocalc
            readOnly: false
